### PR TITLE
Gradio UI

### LINKED ISSUE #9: Feature request: provide a gradio gui
I think it would make this extension more accessible to provide a gradio gui that calls the cli script.

### PR DESCRIPTION
**Pull request by ljleb**
Add a gradio ui to start the script from within the webui. I'll add a preview of what it looks like when done with the location of the settings in the page.

As of right now, it does not improve the experience by much for new users, but at least you can click on buttons now instead of having to use the command line.

Remains to be done:

- [x] rearrange the components into a compact cols/rows structure
- [ ] display the nice unet weights chart at the end of the optimiser process
- [x] manual test to make sure I didn't miss something (especially when calling the script)

We should consider adding a (sub-)tab to display arbitrary unet merge results without having to merge. I think it is a bit out of scope of this PR, let me know if you want me to add that.

Feel free to request changes or edit this PR.

Closes #9

### CODE REVIEW

**Comment by ljleb** [comment]
Quick ack:

My intention is to provide an additional way of using the optimisers. We can remove the cli if you want, but this PR does not change this part of the code in any way, except for sharing defaults and limited choices. (i.e. safetensors vs ckpt for `--best_format`)

At the moment the ui simply forwards the specified values to the cli script, it does not remove it or change its internal behaviour. It is called here:

https://github.com/s1dlx/sd-webui-bayesian-merger/blob/11101f1cb719c689410f1f463bd93b5894b3d1aa/scripts/optimiser_gui.py#L208

Maybe this is not necessary, I could make a direct call to `bayesian_merger.main` as an alternative.

I tried to keep the ui code as tidy as I could. The only part of the code that is shared with the cli right now is the new `sd_webui_bayesian_merger.cli_args` module, which exposes in a single location the defaults and choices of the command line arguments and of the user interface.

**Comment by ljleb** [comment]
Does this look good enough for you? I can move stuff around a bit if you don't like it. I'll be honest, I took a bit of inspiration from the supermerger extension for the placement because I never really tried to put together a convenient user interface before.

image

**Comment by s1dlx** [comment]
Love it!

how difficult would be to have a menu to select the scorer model instead of typing the name? 

Yes, that is the clip skip value.

**Comment by ljleb** [comment]
Thanks!

I was thinking of adding a file picker instead, for example in case you want to use a finetuned scorer or just any model that uses the structure of one of the supported types.

Alternatively, I can create a dropdown based on the selected folder perhaps? And then add a refresh button to fill the dropdown with the contents of the folder.

**Comment by s1dlx** [comment]
No strong opinion on this tbh

perhaps we should follow the drop down + refresh button that seems to be used a lot in webui

**Comment by ljleb** [comment]
I agree. I think the scorer directory could be a setting in the options tab.

We may want to add `<a1111 sd webui root>/models/scorer` to search paths by default on top of the path relative to the extension.

**Comment by ljleb** [comment]
> An idea may be to let the user define all the parameters in the config files, while the GUI contains only results/images/plots

Yes that is what is implemented in the interface at the moment, although I believe some of the options dont necessarily make sense because I have not used the extension enough to understand the purpose of everything. I think this is similar to how you need to configure bmaltais/kohya_ss before creating a lora.

I have a couple PRs open here and there in different repos, I need to actually finish the work and I will have to prioritize. I am also a little busy at the moment so if you or someone else want to look into finishing this or take inspiration from the ui code that is already there feel free to do it.

Except for how the gradio components are declared (i.e. using metaclasses), i think the code is structured in a way that allows easier maintainability, by separating the components in 1) definition, 2) organisation, and 3)

**Comment by ljleb** [comment]
Did not intend to close, I misclicked the button while typing my response.

**Comment by ljleb** [comment]
So for payloads, it makes sense to ask for a path and have users manually edit the payloads I think. For all other config parameters however, I think it makes more sense to have them in the gradio ui.

This means bypassing the hydra config files to launch the optimizer, and also having to maintain the ui parameters whenever new configuration options are added or old ones are removed. We can load the configuration from /conf for default ui values.

So there is a tradeoff of code maintenance vs more convenience on the usage side, if we do this instead of just asking for the hydra config path.

**Comment by ljleb** [comment]
For now I'll remove the ui components and use the config directly. We can look into an easier way to maintain the parameters later, and provide the ui parameters corresponding to the config whenever it is easier to keep everything up to date.

**Pull request closed without merging**
